### ISSUE TITLE
Doch keine Gradle!

### ISSUE THREAD

**Issue by gallexander** [gallexander/schnitzeljagd#1]
Habe mich doch dazu entschieden kein Gradle zu verwenden, da dadurch die neueste Version von Play nicht unterstützt wird!
Maven wird stattdessen verwendet, aber auch erst wenn es soweit ist, also externe Abhängigkeiten hinzugefügt werden müssen. Also vorerst ist mal nur Play interessant.

**Comment by gallexander** [comment]
Habe mich doch dazu entschieden kein Gradle zu verwenden, da dadurch die neueste Version von Play nicht unterstützt wird!
Maven wird stattdessen verwendet, aber auch erst wenn es soweit ist, also externe Abhängigkeiten hinzugefügt werden müssen.

**Comment by MartinGallauner** [comment]
alles klar
