### ISSUE TITLE
SBT

### ISSUE THREAD

**Issue by MartinGallauner** [gallexander/schnitzeljagd#2]
Hallo Hallo!

Ich habe mir jetzt den sbt beginner guide vorgeknöpft.
Glaube jetzt zu verstehen für was wir das brauchen könnten ;)

Sollten wir nicht auch einen src/ haben?

**Comment by gallexander** [comment]
Nö brauchen wir nicht, es ist nur wichtig, dass du die sbt befehle in bezug
auf das play framework verstehst
z.B sbt run im Projektordner

Am 02.07.2017 08:48 schrieb "Martin" <notifications@github.com>:

**Comment by MartinGallauner** [comment]
Habe gerade das Projekt über den Intellij zum laufen gebraucht.

Fühle mich gerade wie Tom Hanks bei Cast Away wie er zum ersten mal Feuer gemacht hat ;)

**Comment by gallexander** [comment]
Das glaube ich dir! :-)
An was ist es gelegen?

Am 02.07.2017 20:23 schrieb "Martin" <notifications@github.com>:

**Comment by MartinGallauner** [comment]
Die vorigen Fehlermeldungen waren eigentlich nur beim importieren des Projektes da.

Habe mir auf der Seite vom Play Framework einen Beginner Guide durchgelesen, der hat erklärt wie man diesen run task erstellt.
Hat dann bisschen gerattert aber hat dann schließlich funktioniert.

Habe da den Eindruck dass der Mac da ruhig ein bisschen mehr Power vertragen könnte

**Comment by gallexander** [comment]
Naja die CPU hat doch eh nen turbo! :-)
IDEA ist halt ein ziemlich cpulastiger IDE! Da ist mir eclipse immer
schneller vorgekommen

Am 03.07.2017 09:17 schrieb "Martin" <notifications@github.com>:
